# -*- coding: utf-8 -*-
"""M/C.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qG9Zx1SvK-Df170Gwf4Q7ePQ0IwY2kvK
"""

from IPython.display import clear_output
boat_side= "Right"
missionaries_on_right=3
cannibals_on_right=3
missionaries_on_left=0
cannibals_on_left =0

print("\U0001f482" * missionaries_on_left,
      "\U0001f479" * cannibals_on_left,
      "\U0001f30a" * 5 + "\U0001f6A2",
      "\U0001f482" * missionaries_on_right,
      "\U0001f479" * cannibals_on_right)

while True:
  missionaries=int(input("enter number of missionaries u want to be on boat"))
  cannibals=int(input("enter number of cannibals u want to be on boat "))
  boat_passengers=missionaries+cannibals

  if (1<=boat_passengers<=2):
    print("ur move is valid ")
  else:
      print("ur move is invalid ")
      continue


  if (boat_side=="Right"):
    print(" the boat is on right side")

    if missionaries > missionaries_on_right or cannibals >cannibals_on_right:
      print("invalid move2")
      continue
    else:
      print("valid move")
    missionaries_on_right=missionaries_on_right -missionaries
    missionaries_on_left=missionaries_on_left+missionaries
    cannibals_on_right= cannibals_on_right -cannibals
    cannibals_on_left=cannibals_on_left+cannibals
    boat_side = "Left"
    clear_output()
    print("\U0001f482" * missionaries_on_left,
      "\U0001f479" * cannibals_on_left,
      "\U0001f6A2" + "\U0001f30a" * 5,
      "\U0001f482" * missionaries_on_right,
      "\U0001f479" * cannibals_on_right)
  elif(boat_side== "Left"):
    print("boat on left bank ")

    if missionaries > missionaries_on_left or cannibals >cannibals_on_left:
      print("invalid move2")
      continue
    else:
      print("valid move")
    missionaries_on_left=missionaries_on_left-missionaries
    missionaries_on_right=missionaries_on_right+missionaries
    cannibals_on_left=cannibals_on_left-cannibals
    cannibals_on_right=cannibals_on_right+cannibals
    clear_output()
    print("\U0001f482" * missionaries_on_left,
      "\U0001f479" * cannibals_on_left,
      "\U0001f6A2" + "\U0001f30a" * 5,
      "\U0001f482" * missionaries_on_right,
      "\U0001f479" * cannibals_on_right)
  if(missionaries_on_right<cannibals_on_right and  missionaries_on_right>0 ):
    print( "u lose ")
  elif(missionaries_on_left<cannibals_on_left and missionaries_on_left>0):
    print("u lose ")
    break
  if( missionaries_on_right and cannibals_on_right==3):
    print("u win ")
    break